# Dataset

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('penguins.csv',index_col=0)
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
1  Adelie  Torgersen            39.1           18.7              181.0   
2  Adelie  Torgersen            39.5           17.4              186.0   
3  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen             NaN            NaN                NaN   
5  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  year  
1       3750.0    male  2007  
2       3800.0  female  2007  
3       3250.0  female  2007  
4          NaN     NaN  2007  
5       3450.0  female  2007

In [7]:
# Shape of data
df.shape

(344, 8)

In [8]:
# 결측치 확인
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [9]:
# 결측치 제거
df = df.dropna().reset_index(drop=True)

In [10]:
# 결측치 확인
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
dtype: int64

연도 변수는 독립 변수에서 제외

In [11]:
df = df.iloc[:,:-1]
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen            36.7           19.3              193.0   
4  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  
0       3750.0    male  
1       3800.0  female  
2       3250.0  female  
3       3450.0  female  
4       3650.0    male

In [12]:
df.shape

(333, 7)

In [13]:
# Convert categorical variable into dummy

island_dummies = pd.get_dummies(df.island)
sex_dummies = pd.get_dummies(df.sex)

In [14]:
island_dummies.head()

Biscoe  Dream  Torgersen
0   False  False       True
1   False  False       True
2   False  False       True
3   False  False       True
4   False  False       True

## Concatenate dataframe

In [15]:
df = pd.concat([df,island_dummies,sex_dummies],axis=1)
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen            36.7           19.3              193.0   
4  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  Biscoe  Dream  Torgersen  female   male  
0       3750.0    male   False  False       True   False   True  
1       3800.0  female   False  False       True    True  False  
2       3250.0  female   False  False       True    True  False  
3       3450.0  female   False  False       True    True  False  
4       3650.0    male   False  False       True   False   True

In [16]:
df = df.drop(['island','sex'],axis=1)
df.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0  Adelie            39.1           18.7              181.0       3750.0   
1  Adelie            39.5           17.4              186.0       3800.0   
2  Adelie            40.3           18.0              195.0       3250.0   
3  Adelie            36.7           19.3              193.0       3450.0   
4  Adelie            39.3           20.6              190.0       3650.0   

   Biscoe  Dream  Torgersen  female   male  
0   False  False       True   False   True  
1   False  False       True    True  False  
2   False  False       True    True  False  
3   False  False       True    True  False  
4   False  False       True   False   True

In [17]:
df.shape

(333, 10)

## Labels

In [18]:
df.species.value_counts()

species
Adelie       146
Gentoo       119
Chinstrap     68
Name: count, dtype: int64

In [19]:
# 문자열 형태를 정수형으로 변환
def make_int(s):
  if s == 'Adelie':
    return 0
  elif s == 'Gentoo':
    return 1
  else:
    return 2

In [20]:
df['species'] = df.species.apply(make_int)

In [21]:
df.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0        0            39.1           18.7              181.0       3750.0   
1        0            39.5           17.4              186.0       3800.0   
2        0            40.3           18.0              195.0       3250.0   
3        0            36.7           19.3              193.0       3450.0   
4        0            39.3           20.6              190.0       3650.0   

   Biscoe  Dream  Torgersen  female   male  
0   False  False       True   False   True  
1   False  False       True    True  False  
2   False  False       True    True  False  
3   False  False       True    True  False  
4   False  False       True   False   True

나중에 one-hot encoding을 위해서는 정수형으로 바꿔주어야 함

# Holdout

In [22]:
from sklearn.model_selection import train_test_split
import numpy as np
import tensorflow as tf

2023-07-06 17:15:13.346125: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-06 17:15:13.398798: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-06 17:15:13.399579: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-06 17:15:14.071766: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [23]:
np.set_printoptions(suppress=True)

In [24]:
x = df.iloc[:,1:].values
y = df.iloc[:,0]

In [25]:
x[0]

array([39.1, 18.7, 181.0, 3750.0, False, False, True, False, True],
      dtype=object)

In [26]:
y[0]

0

In [27]:
# One-hot encoding
y_one_hot = tf.keras.utils.to_categorical(y)

In [28]:
y_one_hot[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [29]:
x_train, x_test, y_train, y_test = train_test_split(x,y_one_hot,test_size=0.1,shuffle=True)

In [30]:
print('Shape of x train : ',x_train.shape)
print('Shape of x test : ',x_test.shape)
print('Shape of y train : ',y_train.shape)
print('Shape of y test : ',y_test.shape)

Shape of x train :  (299, 9)
Shape of x test :  (34, 9)
Shape of y train :  (299, 3)
Shape of y test :  (34, 3)


## Scaling

In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
scaler = StandardScaler()

In [33]:
x_train[:,:-5]

array([[36.5, 16.6, 181.0, 2850.0],
       [39.7, 17.7, 193.0, 3200.0],
       [50.8, 19.0, 210.0, 4100.0],
       ...,
       [46.5, 14.5, 213.0, 4400.0],
       [42.7, 13.7, 208.0, 3950.0],
       [50.9, 17.9, 196.0, 3675.0]], dtype=object)

In [34]:
scaler.fit(x_train[:,:-5])

StandardScaler()

In [35]:
x_train_std = scaler.transform(x_train[:,:-5])
x_test_std = scaler.transform(x_test[:,:-5])

In [36]:
x_train_std[0]

array([-1.37460521, -0.30935142, -1.40599243, -1.68660548])

In [37]:
x_train_std = np.concatenate([x_train_std,x_train[:,-5:]],axis=1)
x_test_std = np.concatenate([x_test_std,x_test[:,-5:]],axis=1)

In [38]:
x_train_std[0]

array([-1.3746052137494187, -0.30935142030336366, -1.405992432598313,
       -1.686605479013658, True, False, False, True, False], dtype=object)

In [39]:
x_test_std[0]

array([-0.6997768365712609, -0.05496177599449401, -0.5506684502038157,
       -0.9993422168596693, False, True, False, True, False], dtype=object)

# Model

# Model

- 첫 번째 은닉층의 node 수는 256
- 두 번째 은닉층의 node 수는 128
- 두 번째 은닉층 이후에 Dropout 적용
- 모든 활성화 함수는 ReLU(분류 층 제외)

## Sequential

### 시각화

In [40]:
import matplotlib.pyplot as plt

### 평가

첫 번째가 손실, 두 번째가 정확도

### 추론

## Funtional

Skip connection 등과 같이 층들과의 또 다른 관계식을 표현할 때는 단순히 연속적으로 층을 쌓아서는 할 수 없음. 이러한 부분을 해결하기 위해서는 기능적으로 층을 쌓아야함

### Early stopping & Model checkpoint

- patience : 얼마나 오랫동안 변화가 없으면 학습을 멈출 것인지를 정하는 인자

- monitor : 어떠한 지표를 참고할 것인지
- mode : monitor로 관찰하는 지표가 최저일 때를 기준으로 볼 것인지, 최고를 기준으로 볼것인지

## 객체

### Gradient Tape

In [ ]:
loss_object = tf.keras.losses.CategoricalCrossentropy()
optimizer = tf.keras.optimizers.Adam()

In [ ]:
train_loss = tf.keras.metrics.Mean(name='train_loss')
train_accuracy = tf.keras.metrics.CategoricalAccuracy(name='train_accuracy')

In [ ]:
@tf.function
def train_step(model,inputs,labels,loss_object,optimizer,train_loss,train_metric):
  with tf.GradientTape() as tape:
    preds = model(inputs)
    loss = loss_object(labels,preds)
  gradients = tape.gradient(loss, model.trainable_variables)

  optimizer.apply_gradients(zip(gradients,model.trainable_variables))
  train_loss(loss)
  train_metric(labels,preds)


In [ ]:
for epoch in range(10):
  for x, label in train_ds:
    train_step(model,x,label,loss_object,optimizer,train_loss,train_accuracy)

  print('Epoch : {} Loss : {} Accuracy : {}'.format(epoch,train_loss.result(),train_accuracy.result()*100))

Epoch : 0 Loss : 0.011812306940555573 Accuracy : 99.33110809326172
Epoch : 1 Loss : 0.007976454682648182 Accuracy : 99.6655502319336
Epoch : 2 Loss : 0.008113743737339973 Accuracy : 99.6655502319336
Epoch : 3 Loss : 0.006807760801166296 Accuracy : 99.7491683959961
Epoch : 4 Loss : 0.006038080435246229 Accuracy : 99.79933166503906
Epoch : 5 Loss : 0.005408630706369877 Accuracy : 99.83277130126953
Epoch : 6 Loss : 0.004990162327885628 Accuracy : 99.85665893554688
Epoch : 7 Loss : 0.004604077897965908 Accuracy : 99.87458038330078
Epoch : 8 Loss : 0.004298255778849125 Accuracy : 99.88851928710938
Epoch : 9 Loss : 0.004038689658045769 Accuracy : 99.89966583251953
