# Dataset

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('penguins.csv',index_col=0)
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
1  Adelie  Torgersen            39.1           18.7              181.0   
2  Adelie  Torgersen            39.5           17.4              186.0   
3  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen             NaN            NaN                NaN   
5  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  year  
1       3750.0    male  2007  
2       3800.0  female  2007  
3       3250.0  female  2007  
4          NaN     NaN  2007  
5       3450.0  female  2007

In [3]:
# Shape of data
df.shape

(344, 8)

In [4]:
# 결측치 확인
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [5]:
# 결측치 제거
df = df.dropna().reset_index(drop=True)

In [6]:
# 결측치 확인
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
dtype: int64

연도 변수는 독립 변수에서 제외

In [7]:
df = df.iloc[:,:-1]
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen            36.7           19.3              193.0   
4  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  
0       3750.0    male  
1       3800.0  female  
2       3250.0  female  
3       3450.0  female  
4       3650.0    male

In [8]:
df.shape

(333, 7)

In [9]:
# Convert categorical variable into dummy

island_dummies = pd.get_dummies(df.island)
sex_dummies = pd.get_dummies(df.sex)

In [10]:
island_dummies.head()

Biscoe  Dream  Torgersen
0   False  False       True
1   False  False       True
2   False  False       True
3   False  False       True
4   False  False       True

## Concatenate dataframe

In [11]:
df = pd.concat([df,island_dummies,sex_dummies],axis=1)
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen            36.7           19.3              193.0   
4  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  Biscoe  Dream  Torgersen  female   male  
0       3750.0    male   False  False       True   False   True  
1       3800.0  female   False  False       True    True  False  
2       3250.0  female   False  False       True    True  False  
3       3450.0  female   False  False       True    True  False  
4       3650.0    male   False  False       True   False   True

In [12]:
df = df.drop(['island','sex'],axis=1)
df.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0  Adelie            39.1           18.7              181.0       3750.0   
1  Adelie            39.5           17.4              186.0       3800.0   
2  Adelie            40.3           18.0              195.0       3250.0   
3  Adelie            36.7           19.3              193.0       3450.0   
4  Adelie            39.3           20.6              190.0       3650.0   

   Biscoe  Dream  Torgersen  female   male  
0   False  False       True   False   True  
1   False  False       True    True  False  
2   False  False       True    True  False  
3   False  False       True    True  False  
4   False  False       True   False   True

In [13]:
df.shape

(333, 10)

## Labels

In [14]:
df.species.value_counts()

species
Adelie       146
Gentoo       119
Chinstrap     68
Name: count, dtype: int64

In [15]:
# 문자열 형태를 정수형으로 변환
def make_int(s):
  if s == 'Adelie':
    return 0
  elif s == 'Gentoo':
    return 1
  else:
    return 2

In [16]:
df['species'] = df.species.apply(make_int)

In [17]:
df.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0        0            39.1           18.7              181.0       3750.0   
1        0            39.5           17.4              186.0       3800.0   
2        0            40.3           18.0              195.0       3250.0   
3        0            36.7           19.3              193.0       3450.0   
4        0            39.3           20.6              190.0       3650.0   

   Biscoe  Dream  Torgersen  female   male  
0   False  False       True   False   True  
1   False  False       True    True  False  
2   False  False       True    True  False  
3   False  False       True    True  False  
4   False  False       True   False   True

나중에 one-hot encoding을 위해서는 정수형으로 바꿔주어야 함

# Holdout

In [18]:
from sklearn.model_selection import train_test_split
import numpy as np
# import tensorflow as tf

In [19]:
np.set_printoptions(suppress=True)

In [20]:
x = df.iloc[:,1:].values
y = df.iloc[:,0]

In [21]:
x[0]

array([39.1, 18.7, 181.0, 3750.0, False, False, True, False, True],
      dtype=object)

In [22]:
y = y.values

Pytorch는 별도의 one-hot encoding이 필요 없음

In [23]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.1,shuffle=True)
x_train, x_valid, y_train, y_valid = train_test_split(x_train,y_train,test_size=0.1,shuffle=True)

In [24]:
print('Shape of x train : ',x_train.shape)
print('Shape of x test : ',x_test.shape)
print('Shape of x valid : ',x_valid.shape)

print('Shape of y train : ',y_train.shape)
print('Shape of y valid : ',y_valid.shape)
print('Shape of y test : ',y_test.shape)

Shape of x train :  (269, 9)
Shape of x test :  (34, 9)
Shape of x valid :  (30, 9)
Shape of y train :  (269,)
Shape of y valid :  (30,)
Shape of y test :  (34,)


In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
scaler = StandardScaler()

In [27]:
x_train[:,:-5]

array([[46.3, 15.8, 215.0, 5050.0],
       [52.7, 19.8, 197.0, 3725.0],
       [41.0, 20.0, 203.0, 4725.0],
       ...,
       [46.8, 16.1, 215.0, 5500.0],
       [39.6, 18.1, 186.0, 4450.0],
       [41.1, 18.1, 205.0, 4300.0]], dtype=object)

In [28]:
scaler.fit(x_train[:,:-5])

StandardScaler()

In [29]:
x_train_std = scaler.transform(x_train[:,:-5])
x_valid_std = scaler.transform(x_valid[:,:-5])
x_test_std = scaler.transform(x_test[:,:-5])

In [30]:
x_train_std[0]

array([ 0.41679492, -0.70902194,  0.99058694,  1.03674178])

In [31]:
x_train_std = np.concatenate([x_train_std,x_train[:,-5:]],axis=1)
x_valid_std = np.concatenate([x_valid_std,x_valid[:,-5:]],axis=1)
x_test_std = np.concatenate([x_test_std,x_test[:,-5:]],axis=1)

In [32]:
x_train_std[0]

array([0.4167949231924065, -0.7090219364462274, 0.9905869443842509,
       1.0367417820077298, True, False, False, False, True], dtype=object)

In [33]:
x_valid_std[0]

array([1.2486667360933414, 0.6767763209296961, 0.0034076819997339103,
       0.29560514767687995, False, True, False, False, True], dtype=object)

In [34]:
x_test_std[0]

array([-0.4705350105685901, 0.6767763209296961, 0.0034076819997339103,
       -0.26024732807125744, False, True, False, False, True],
      dtype=object)

# Torch dataset

In [35]:
import torch
from torch.utils.data import Dataset, TensorDataset,DataLoader

/home/xogns5037/.conda/envs/th/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


### Tensor dataset

In [36]:
x_train_std = x_train_std.astype(np.float32) 
x_valid_std = x_valid_std.astype(np.float32)
x_test_std = x_test_std.astype(np.float32)

In [37]:
x_train_tensor = torch.tensor(x_train_std,dtype=torch.float32)
x_valid_tensor = torch.tensor(x_valid_std,dtype=torch.float32)
x_test_tensor = torch.tensor(x_test_std,dtype=torch.float32)

In [38]:
y_train_tensor = torch.LongTensor(y_train)
y_valid_tensor = torch.LongTensor(y_valid)
y_test_tensor = torch.LongTensor(y_test)

TensorDataset function을 사용하기 위해서는 사전에 data들을 위와 같이 float 형식과 long 형식으로 맞춰주어야 한다

In [39]:
trainset = TensorDataset(x_train_tensor,y_train_tensor)
validset = TensorDataset(x_valid_tensor,y_valid_tensor)
testset = TensorDataset(x_test_tensor,y_test_tensor)

In [40]:
trainloader = DataLoader(trainset,batch_size=32,shuffle=True)
validloader = DataLoader(validset,batch_size=32)
testloader = DataLoader(testset,batch_size=32)

In [41]:
next(iter(trainloader)) # next(iter(trainloader)) : trainloader의 첫번째 배치를 반환

[tensor([[-0.5445,  0.9334, -1.3363, -0.9705,  0.0000,  1.0000,  0.0000,  0.0000,
           1.0000],
         [-0.8403,  0.1122, -1.0543, -0.5073,  0.0000,  0.0000,  1.0000,  1.0000,
           0.0000],
         [ 1.0638, -0.1958,  2.0483,  1.8396,  1.0000,  0.0000,  0.0000,  0.0000,
           1.0000],
         [-1.5797,  0.1635, -0.7722, -0.6308,  0.0000,  0.0000,  1.0000,  1.0000,
           0.0000],
         [-1.0621,  1.0361, -0.8427, -0.3220,  0.0000,  1.0000,  0.0000,  0.0000,
           1.0000],
         [-1.6536,  1.1387, -0.5607, -0.0132,  0.0000,  0.0000,  1.0000,  0.0000,
           1.0000],
         [ 1.5075,  0.8308, -0.2786, -0.9396,  0.0000,  1.0000,  0.0000,  0.0000,
           1.0000],
         [ 1.4705,  1.8059,  0.6380,  0.7279,  0.0000,  1.0000,  0.0000,  0.0000,
           1.0000],
         [-0.4705,  0.5741, -0.4197,  0.1103,  0.0000,  0.0000,  1.0000,  0.0000,
           1.0000],
         [ 0.9159, -0.5550,  1.0611,  1.6544,  1.0000,  0.0000,  0.0000,  0.0000,


Tensordataset 함수 같은 경우는 위와 같이 간단한 vector -> torch tensor로 바꿀 때 유용하다

### Custom dataset

In [42]:
# torch.utils.data.Dataset의 기능들을 상속
class MyDataset(Dataset):

  def __init__(self,x,y):

    self.x = x
    self.y = y

  def __len__(self):
    return len(self.x)

  def __getitem__(self,idx):
    x = torch.tensor(self.x[idx],dtype=torch.float32)
    y = torch.tensor(self.y[idx]).long()
    return x,y

Custom dataset의 경우에는 크게 3 가지 instance method로 구성되어 있다.

- __init__(self)은 어떠한 data를 받아서 dataset으로 바꿀 건지에 대해서 정해준다

- __len__(self) : dataset의 크기를 반환해준다
- __getitem__(self,idx) : Dataest의 특정 식별자를 검색할 수 있도록 해준다.

In [43]:
trainset = MyDataset(x_train_std,y_train)
validset = MyDataset(x_valid_std,y_valid)
testset = MyDataset(x_test_std,y_test)

In [44]:
trainset.__getitem__(1)

(tensor([ 1.5999,  1.3440, -0.2786, -0.5999,  0.0000,  1.0000,  0.0000,  0.0000,
          1.0000]),
 tensor(2))

In [45]:
trainloader = DataLoader(trainset,batch_size=32)
validloader = DataLoader(validset,batch_size=32)
testloader = DataLoader(testset,batch_size=32)

In [46]:
next(iter(trainloader))

[tensor([[ 0.4168, -0.7090,  0.9906,  1.0367,  1.0000,  0.0000,  0.0000,  0.0000,
           1.0000],
         [ 1.5999,  1.3440, -0.2786, -0.5999,  0.0000,  1.0000,  0.0000,  0.0000,
           1.0000],
         [-0.5630,  1.4467,  0.1444,  0.6353,  1.0000,  0.0000,  0.0000,  0.0000,
           1.0000],
         [ 0.1950, -1.3763,  0.9906,  0.9750,  1.0000,  0.0000,  0.0000,  1.0000,
           0.0000],
         [ 0.8050, -1.3249,  0.8496,  2.0249,  1.0000,  0.0000,  0.0000,  0.0000,
           1.0000],
         [ 0.4353, -0.8117,  1.4137,  0.9750,  1.0000,  0.0000,  0.0000,  0.0000,
           1.0000],
         [-0.8403,  0.1122, -1.0543, -0.5073,  0.0000,  0.0000,  1.0000,  1.0000,
           0.0000],
         [ 0.9529,  0.5228, -0.4197,  0.2338,  0.0000,  1.0000,  0.0000,  0.0000,
           1.0000],
         [ 1.3411,  0.5228, -0.2786, -0.5691,  0.0000,  1.0000,  0.0000,  0.0000,
           1.0000],
         [-0.8218,  1.8059, -0.7017, -0.3838,  1.0000,  0.0000,  0.0000,  1.0000,


# 모형

In [47]:
from torch import nn
from torch import optim

In [48]:
class MyModel(nn.Module):

  def __init__(self):
    #super(MyModel,self).__init__()
    super().__init__()
    '''
    위의 표현이나 아래 표현이나 같은 표현.
    모형을 쌓을 때는 꼭 생성자에 저 부분을 통해서 상속을 받아야 함
    '''
    self.linear1 = nn.Linear(9,64) # Linear : keras에서 Dense
    self.linear2 = nn.Linear(64,128)
    self.relu = nn.ReLU()
    self.dropout = nn.Dropout(0.5)
    self.output = nn.Linear(128,3)

  def forward(self,x): # x : input / forward : keras에서는 call
    x = self.linear1(x)
    x = self.relu(x)
    x = self.linear2(x)
    x = self.relu(x)
    x = self.dropout(x)
    out = self.output(x)
    return out

In [49]:
import torch

In [50]:
# GPU 사용 확인
torch.cuda.is_available()

True

In [51]:
# Set device
# 간단하게 device = 'cuda' 라고 써도됨
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [52]:
model = MyModel().to(device)

CPU를 사용할 경우 to(device)를 통해 담아줄 필요는 없음

In [53]:
# 모형 구조 확인
model

MyModel(
  (linear1): Linear(in_features=9, out_features=64, bias=True)
  (linear2): Linear(in_features=64, out_features=128, bias=True)
  (relu): ReLU()
  (dropout): Dropout(p=0.5, inplace=False)
  (output): Linear(in_features=128, out_features=3, bias=True)
)

In [54]:
from torchsummary import summary

In [55]:
# 모형 요약
summary(model,input_size=(9,))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                   [-1, 64]             640
              ReLU-2                   [-1, 64]               0
            Linear-3                  [-1, 128]           8,320
              ReLU-4                  [-1, 128]               0
           Dropout-5                  [-1, 128]               0
            Linear-6                    [-1, 3]             387
Total params: 9,347
Trainable params: 9,347
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.04
Estimated Total Size (MB): 0.04
----------------------------------------------------------------


## 학습

In [56]:
# 손실 함수
loss_fn = nn.CrossEntropyLoss() # 분류문제
# Optimizer
optimizer = optim.Adam(model.parameters(), lr=1e-4)

Optimizer에는 해당 함수가 어떠한 모형의 가중치들로 최신화를 할 것인지 담아주어야 함. 이를 위해 인자로 model.parameters()를 넣어줌

In [57]:
for x,y in trainloader:
  sx = x.to(device)
  sy = y.to(device)
  break

In [58]:
model(sx).shape

torch.Size([32, 3])

In [59]:
sy

tensor([0, 0, 2, 0, 2, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 2, 2, 1, 2, 0, 0, 1, 2,
        2, 0, 0, 0, 1, 2, 2, 0], device='cuda:0')

In [60]:
loss_fn(model(sx),sy).item()

1.1002806425094604

In [61]:
len(trainloader.dataset)

269

In [62]:
len(trainloader)

9

In [63]:
# 학습 함수

def train(model,dataloader,loss_fn,optimizer):
  # 학습 선언
  model.train()
  size = len(dataloader.dataset)
  total_batch = len(dataloader)
  running_loss = 0
  accuracy = 0

  for batch, (x,y) in enumerate(dataloader):
    x = x.to(device) # GPU의 경우 변수들도 device 해줘야함
    y = y.to(device)
    preds = model(x)
    loss = loss_fn(preds,y)
    acc = (preds.argmax(1) == y).sum().item()
    accuracy += acc
    batch_acc = acc / len(x)

    # 경사 초기화
    optimizer.zero_grad()
    # 역전파
    loss.backward()
    optimizer.step()

    running_loss += loss.item()

    print(f'Batch {batch} loss : {loss.item():>7f}\tBatch {batch} accuracy : {np.round(batch_acc,2)*100}   [{batch*32}/{size}]')

  final_loss = running_loss / total_batch
  final_accuracy = accuracy / size
  return final_loss,final_accuracy


In [64]:
for epoch in range(1,101):
  print('Epoch ',epoch)
  loss,acc = train(model,trainloader,loss_fn,optimizer)
  print(f'Epoch {epoch}\nLoss : {loss}\tAccuracy : {acc}\n')

Epoch  1
Batch 0 loss : 1.082282	Batch 0 accuracy : 38.0   [0/269]
Batch 1 loss : 1.076678	Batch 1 accuracy : 44.0   [32/269]
Batch 2 loss : 1.104151	Batch 2 accuracy : 25.0   [64/269]
Batch 3 loss : 1.051355	Batch 3 accuracy : 50.0   [96/269]
Batch 4 loss : 1.076806	Batch 4 accuracy : 31.0   [128/269]
Batch 5 loss : 1.104732	Batch 5 accuracy : 25.0   [160/269]
Batch 6 loss : 1.063401	Batch 6 accuracy : 53.0   [192/269]
Batch 7 loss : 1.074686	Batch 7 accuracy : 44.0   [224/269]
Batch 8 loss : 1.092731	Batch 8 accuracy : 46.0   [256/269]
Epoch 1
Loss : 1.0807580285602145	Accuracy : 0.3903345724907063

Epoch  2
Batch 0 loss : 1.056554	Batch 0 accuracy : 59.0   [0/269]
Batch 1 loss : 1.069243	Batch 1 accuracy : 38.0   [32/269]
Batch 2 loss : 1.090175	Batch 2 accuracy : 38.0   [64/269]
Batch 3 loss : 1.070835	Batch 3 accuracy : 47.0   [96/269]
Batch 4 loss : 1.062308	Batch 4 accuracy : 41.0   [128/269]
Batch 5 loss : 1.066946	Batch 5 accuracy : 41.0   [160/269]
Batch 6 loss : 1.067603	Bat

# 평가

In [65]:
# 평가 함수

def test(model,dataloader,loss_fn):
  # 평가 선언 -> 경사가 활용되지 않음
  model.eval()
  size = len(dataloader.dataset)
  total_batch = len(dataloader)
  test_loss,test_acc = 0, 0

  # 경사 사용 X
  with torch.no_grad():
    for batch, (x,y) in enumerate(dataloader):
      x = x.to(device)
      y = y.to(device)

      preds = model(x)
      loss = loss_fn(preds,y)
      test_acc += (preds.argmax(1) == y).sum().item()
      test_loss += loss.item()

    test_loss /= total_batch
    test_acc /= size

  return test_loss,test_acc

In [66]:
test(model,validloader,loss_fn)

(0.02598966285586357, 1.0)

## 조기 종료 및 모형 저장

In [67]:
import copy

In [68]:
best_loss = 999999
# 현재 모형 가중치 저장
best_model_weight = copy.deepcopy(model.state_dict())
# 조기 종료 patience
patience = 5
# Current patience
cur_patience = 0

for epoch in range(1,101):
  print('Epoch : ',epoch)
  train_loss,train_acc = train(model,trainloader,loss_fn,optimizer)
  print(f'Epoch {epoch}\nTrain loss : {train_loss}\tTrain acc : {train_acc}')
  val_loss,val_acc = test(model,validloader,loss_fn)
  print(f'Val loss : {val_loss}\tVal acc : {val_acc}')

  if val_loss < best_loss:
    best_loss = val_loss
    best_model_weight = copy.deepcopy(model.state_dict())
  else:
    cur_patience += 1
    if cur_patience == patience:
      print('Early stopping in epoch ',epoch)
      break

Epoch :  1
Batch 0 loss : 0.026677	Batch 0 accuracy : 100.0   [0/269]
Batch 1 loss : 0.052764	Batch 1 accuracy : 100.0   [32/269]
Batch 2 loss : 0.034928	Batch 2 accuracy : 100.0   [64/269]
Batch 3 loss : 0.033804	Batch 3 accuracy : 100.0   [96/269]
Batch 4 loss : 0.050354	Batch 4 accuracy : 100.0   [128/269]
Batch 5 loss : 0.040606	Batch 5 accuracy : 100.0   [160/269]
Batch 6 loss : 0.066160	Batch 6 accuracy : 97.0   [192/269]
Batch 7 loss : 0.039048	Batch 7 accuracy : 100.0   [224/269]
Batch 8 loss : 0.110661	Batch 8 accuracy : 100.0   [256/269]
Epoch 1
Train loss : 0.05055577618380388	Train acc : 0.9962825278810409
Val loss : 0.02530655264854431	Val acc : 1.0
Epoch :  2
Batch 0 loss : 0.040253	Batch 0 accuracy : 100.0   [0/269]
Batch 1 loss : 0.052685	Batch 1 accuracy : 100.0   [32/269]
Batch 2 loss : 0.044587	Batch 2 accuracy : 100.0   [64/269]
Batch 3 loss : 0.024923	Batch 3 accuracy : 100.0   [96/269]
Batch 4 loss : 0.049043	Batch 4 accuracy : 100.0   [128/269]
Batch 5 loss : 0.0

Batch 4 loss : 0.064161	Batch 4 accuracy : 100.0   [128/269]
Batch 5 loss : 0.030085	Batch 5 accuracy : 100.0   [160/269]
Batch 6 loss : 0.090373	Batch 6 accuracy : 94.0   [192/269]
Batch 7 loss : 0.035417	Batch 7 accuracy : 100.0   [224/269]
Batch 8 loss : 0.036961	Batch 8 accuracy : 100.0   [256/269]
Epoch 10
Train loss : 0.041464885903729334	Train acc : 0.9925650557620818
Val loss : 0.01981009915471077	Val acc : 1.0
Epoch :  11
Batch 0 loss : 0.015775	Batch 0 accuracy : 100.0   [0/269]
Batch 1 loss : 0.046320	Batch 1 accuracy : 100.0   [32/269]
Batch 2 loss : 0.025021	Batch 2 accuracy : 100.0   [64/269]
Batch 3 loss : 0.019380	Batch 3 accuracy : 100.0   [96/269]
Batch 4 loss : 0.056510	Batch 4 accuracy : 97.0   [128/269]
Batch 5 loss : 0.032916	Batch 5 accuracy : 100.0   [160/269]
Batch 6 loss : 0.060736	Batch 6 accuracy : 97.0   [192/269]
Batch 7 loss : 0.021678	Batch 7 accuracy : 100.0   [224/269]
Batch 8 loss : 0.045392	Batch 8 accuracy : 100.0   [256/269]
Epoch 11
Train loss : 0

In [70]:
print(cur_patience)

0


In [71]:
print(best_loss)

0.0025861584581434727


In [72]:
# 모형 저장
model.load_state_dict(best_model_weight)
torch.save(model,'./sample.ckpt')

# 추론

In [73]:
model = torch.load('sample.ckpt')

In [74]:
test(model,testloader,loss_fn)

(0.01101639005355537, 1.0)

In [75]:
for x,y in testloader:
  sx = x.to(device)
  sy = y.to(device)
  break

In [76]:
sam = sx[0]

In [77]:
sam

tensor([-1.0497,  1.0028, -0.8351, -0.3160,  0.0000,  1.0000,  0.0000,  0.0000,
         1.0000], device='cuda:0')

In [78]:
model(sam).argmax()

tensor(0, device='cuda:0')

In [79]:
sy[0]

tensor(0, device='cuda:0')

# Pytorch ligtning

In [62]:
# !pip install pytorch_lightning

In [63]:
import pytorch_lightning as pl

In [ ]:
device = 'cpu'

In [ ]:
class MyModel(pl.LightningModule):

  def __init__(self):
    #super(MyModel,self).__init__()
    super().__init__()
    self.linear1 = nn.Linear(9,256)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(256,128)
    self.dropout = nn.Dropout(0.2)
    self.out = nn.Linear(128,3)

  def forward(self,x):
    x = self.linear1(x)
    x = self.relu(x)
    x = self.linear2(x)
    x = self.relu(x)
    x = self.dropout(x)
    output = self.out(x)
    return output

  def training_step(self,batch,batch_idx):
    x,y = batch
    x = x.to(device)
    y = y.to(device)
    z = self.linear1(x)
    z = self.relu(z)
    z = self.linear2(z)
    z = self.relu(z)
    z = self.dropout(z)
    out = self.out(z)
    loss = nn.CrossEntropyLoss()(out,y)
    self.log('train_loss',loss)
    return loss

  def configure_optimizers(self):
    optimizer = optim.Adam(self.parameters(),lr=1e-3)
    return optimizer

In [ ]:
model = MyModel().to(device)

In [ ]:
trainer = pl.Trainer(max_epochs=100)

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs


In [ ]:
trainer.fit(model,trainloader)

Missing logger folder: /Users/oiehhun/python/2023_여름_코딩스터디/MLP/lightning_logs

  | Name    | Type    | Params
------------------------------------
0 | linear1 | Linear  | 2.6 K 
1 | relu    | ReLU    | 0     
2 | linear2 | Linear  | 32.9 K
3 | dropout | Dropout | 0     
4 | out     | Linear  | 387   
------------------------------------
35.8 K    Trainable params
0         Non-trainable params
35.8 K    Total params
0.143     Total estimated model params size (MB)


Training: 0it [00:00, ?it/s]

/Users/oiehhun/opt/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:432: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 4 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/Users/oiehhun/opt/anaconda3/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py:280: PossibleUserWarning: The number of training batches (9) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  rank_zero_warn(


Epoch 0:   0%|          | 0/9 [00:00<?, ?it/s] 

Epoch 99: 100%|██████████| 9/9 [00:00<00:00, 44.65it/s, v_num=0]

`Trainer.fit` stopped: `max_epochs=100` reached.


Epoch 99: 100%|██████████| 9/9 [00:00<00:00, 39.85it/s, v_num=0]
